In [1]:
import keras

from keras.models import Sequential

from keras.layers import Dense

from keras.datasets import mnist

from keras.optimizers import SGD

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
(X_train,y_train), (X_test,y_test) = mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
X_train[0:1]

array([[[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           3,  18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,
           0,   0,   0

In [5]:
y_train[0:100]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3, 1], dtype=uint8)

In [6]:
X_train = X_train.reshape(60000,784).astype('float32')
X_test = X_test.reshape(10000,784).astype('float32')

In [7]:
X_train[0:1]

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0., 

In [8]:
X_train /= 255
X_test /= 255

In [9]:
X_train[0:1]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

#### One Hot Encoding

In [10]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train,n_classes)
y_test = keras.utils.to_categorical(y_test,n_classes)

In [11]:
y_test[0:1]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)

#### Create Model

In [12]:
model = Sequential()

In [13]:
# first dense hidden layer
model.add(Dense(64,activation='relu',input_shape = (784,)))

In [14]:
# output layer
model.add(Dense(10,activation = 'softmax'))

In [15]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.compile(loss = 'categorical_crossentropy', optimizer=SGD(lr = 0.1), metrics = ['accuracy'])

In [ ]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.4863 - acc: 0.8680 - val_loss: 0.2936 - val_acc: 0.9179
Epoch 2/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.2737 - acc: 0.9223 - val_loss: 0.2407 - val_acc: 0.9306
Epoch 3/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.2285 - acc: 0.9353 - val_loss: 0.2076 - val_acc: 0.9406
Epoch 4/200
60000/60000 [==============================] - 1s 14us/step - loss: 0.1982 - acc: 0.9439 - val_loss: 0.1818 - val_acc: 0.9479
Epoch 5/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.1754 - acc: 0.9505 - val_loss: 0.1662 - val_acc: 0.9539
Epoch 6/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.1583 - acc: 0.9550 - val_loss: 0.1528 - val_acc: 0.9549
Epoch 7/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.1445 - acc: 0.9583 - val_loss: 0.1459 - 

60000/60000 [==============================] - 1s 12us/step - loss: 0.0192 - acc: 0.9969 - val_loss: 0.0852 - val_acc: 0.9750
Epoch 60/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0187 - acc: 0.9968 - val_loss: 0.0848 - val_acc: 0.9757
Epoch 61/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0183 - acc: 0.9970 - val_loss: 0.0858 - val_acc: 0.9759
Epoch 62/200
60000/60000 [==============================] - 1s 11us/step - loss: 0.0178 - acc: 0.9970 - val_loss: 0.0875 - val_acc: 0.9757
Epoch 63/200
60000/60000 [==============================] - 1s 11us/step - loss: 0.0172 - acc: 0.9974 - val_loss: 0.0892 - val_acc: 0.9750
Epoch 64/200
60000/60000 [==============================] - 1s 11us/step - loss: 0.0169 - acc: 0.9975 - val_loss: 0.0917 - val_acc: 0.9742
Epoch 65/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0163 - acc: 0.9977 - val_loss: 0.0868 - val_acc: 0.9766
Epoch 66/200
60000/60000 [==============

Epoch 118/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0053 - acc: 0.9999 - val_loss: 0.0976 - val_acc: 0.9754
Epoch 119/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0053 - acc: 0.9998 - val_loss: 0.0980 - val_acc: 0.9759
Epoch 120/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0052 - acc: 0.9999 - val_loss: 0.0983 - val_acc: 0.9756
Epoch 121/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0051 - acc: 0.9998 - val_loss: 0.0985 - val_acc: 0.9754
Epoch 122/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0050 - acc: 0.9999 - val_loss: 0.0991 - val_acc: 0.9757
Epoch 123/200
60000/60000 [==============================] - 1s 14us/step - loss: 0.0049 - acc: 0.9998 - val_loss: 0.0994 - val_acc: 0.9755
Epoch 124/200
60000/60000 [==============================] - 1s 15us/step - loss: 0.0049 - acc: 0.9999 - val_loss: 0.0984 - val_acc: 0.9759
Epoch 125/200
60000/

60000/60000 [==============================] - 1s 13us/step - loss: 0.0026 - acc: 1.0000 - val_loss: 0.1080 - val_acc: 0.9749
Epoch 177/200
60000/60000 [==============================] - 1s 15us/step - loss: 0.0025 - acc: 1.0000 - val_loss: 0.1079 - val_acc: 0.9753
Epoch 178/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0025 - acc: 1.0000 - val_loss: 0.1079 - val_acc: 0.9754
Epoch 179/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0025 - acc: 1.0000 - val_loss: 0.1084 - val_acc: 0.9756
Epoch 180/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0025 - acc: 1.0000 - val_loss: 0.1080 - val_acc: 0.9752
Epoch 181/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0024 - acc: 1.0000 - val_loss: 0.1091 - val_acc: 0.9751
Epoch 182/200
60000/60000 [==============================] - 1s 14us/step - loss: 0.0024 - acc: 1.0000 - val_loss: 0.1087 - val_acc: 0.9756
Epoch 183/200
60000/60000 [=======